---
- hosts: amazonlinux2
  become: true
  any_errors_fatal: true
  serial: 1
  max_fail_percentage: 0
  vars:
    ansible_user: ec2-user
  ignore_errors: yes
  tasks:
   - name: Rebooting to run this smoothly..
     command: shutdown -r now "Reboot required by ansible"
     async: 0
     poll: 0
     ignore_errors: yes
     register: rebooting


