---
- hosts: windows
  vars:
    ansible_connection: winrm
    ansible_ssh_port: 5986
    anisble_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    validate_certs: false
    ansible_winrm_scheme: https
    ansibe_winrm_read_timeout_sec: 30
    ignore_unreachable: true
    gather_facts: false
  tasks:
  - name: Force update gpo
    win_command: gpupdate/force

  - name: Rebooting a machine with desired updates
    win_reboot:
# One way to ensure the system is reliable, is to set WinRM to a delayed startup
  - name: Ensure WinRM starts when the system has settled and is ready to work reliably
    win_service:
      name: WinRM
      start_mode: delayed

# Additionally, you can add a delay before running the next task
  - name: Reboot a machine that takes time to settle after being booted
    win_reboot:
      post_reboot_delay: 360

# Or you can make win_reboot validate exactly what you need to work before running the next task
  - name: Validate that the netlogon service has started, before running the next task
    win_reboot:
      test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
