---
- hosts: windows
  vars:
    ansible_connection: network_cli
    ansible_ssh_port: 5986
    anisble_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    validate_certs: false
    ansible_winrm_scheme: https
    ansibe_winrm_read_timeout_sec: 30
  tasks:
   - name: Generate logs
     file:
       name: /var/ubuntu
       state: directory

