---
- hosts: webserver
  become: true
  vars:
    ansible_user: ubuntu
  tasks:
   - name: install nginx
     apt: name=nginx state=present update_cache=yes

   - name: ensure nginx started
     service: name=nginx state=restarted enabled=yes


