---
- hosts: webserver
  become: true
  vars:
    ansible_user: ubuntu
  tasks:
   - name: verify nginx service
     command: service nginx status

   - name: verify ngnix is listening on 80
     wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
   - name: verify apache2 service
     command: service apache2 status

   - name: verify apache2 is listening on 80
     wait_for: port=80 timeout=1

- hosts: myotherserver
  become: true
  tasks:
   - name: verify mysql service
     command: service mysql status

   - name: verify mysql is listening on 3306
     wait_for: port=3306 timeout=1



